version: "3"
services:
  app:
    build: ./Dockerfile
    image: adnanrahic/express-docker-app
    deploy:
      replicas: 6
    ports:
      - "80:3000"
    environment:
      - GET_HOSTS_FROM=dns
    labels:
      kompose.service.type: LoadBalancer